version: 2.0

jobs:
  docker-build:
    machine: true
    steps:
        - checkout
        - run: echo $DOCKER_USER
        - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        - run:
            name: build docker image
            command: |
              docker build -t fitboss-frontend:latest .
              docker tag fitboss-frontend:latest whiteclawstudios/fitboss-frontend:latest
              docker push whiteclawstudios/fitboss-frontend:latest

workflows:
  version: 2
  build&test:
    jobs:
      - docker-build
