export const GET_FEE_DUE_DETAILS = 'app/HomePage/GET_FEE_DUE_DETAILS';
export const LOAD_FEE_DUE_DETAILS = 'app/HomePage/LOAD_FEE_DUE_DETAILS';
export const UPDATE_FILTER = 'app/HomePage/UPDATE_FILTER';
export const APPLY_DATE_FILTER = 'app/HomePage/APPLY_DATE_FILTER';
export const UPDATE_SOURCE_DATA = 'app/HomePage/UPDATE_SOURCE_DATA';
export const UPDATE_FEE_DETAILS = 'app/HomePage/UPDATE_FEE_DETAILS';
export const UPDATE_MEMBERSHIP_STATUS = 'app/HomePage/UPDATE_MEMBERSHIP_STATUS';
export const UPDATE_MEMBERSHIP_STATUS_IN_STORE =
  'app/HomePage/UPDATE_MEMBERSHIP_STATUS_IN_STORE';
